anime_mode=off
fidelity=true
sd_mode=clean
sd_override=false
hd_override=true
shaders_enabled=true
sharpen_enabled=true
manual_normal_profile=HQ-HD-FSRCNNX
spatial_active=false
upmix_active=false
night_mode_active=false
up_next_enabled=true
skip_intro_enabled=true
custom_preset=Movie 1080P
