anime_mode=on
fidelity=false
sd_mode=clean
sd_override=false
hd_override=false
shaders_enabled=true
sharpen_enabled=true
manual_normal_profile=nil
spatial_active=false
upmix_active=false
night_mode_active=false
up_next_enabled=true
skip_intro_enabled=true
custom_preset=Anime 1440P+
auto_anime_paths=
